<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFbbuiua\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFbbuiua/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFbbuiua.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFbbuiua\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFbbuiua\appDevDebugProjectContainer([
    'container.build_hash' => 'Fbbuiua',
    'container.build_id' => '142e3304',
    'container.build_time' => 1554978011,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFbbuiua');
