<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(['AppBundle\\Controller\\BookController:edit' => function () {
    return ${($_ = isset($this->services['service_locator.a3kzq15']) ? $this->services['service_locator.a3kzq15'] : $this->load('getServiceLocator_A3kzq15Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\BookController:index' => function () {
    return ${($_ = isset($this->services['service_locator.a3kzq15']) ? $this->services['service_locator.a3kzq15'] : $this->load('getServiceLocator_A3kzq15Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\BookController::edit' => function () {
    return ${($_ = isset($this->services['service_locator.a3kzq15']) ? $this->services['service_locator.a3kzq15'] : $this->load('getServiceLocator_A3kzq15Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\BookController::index' => function () {
    return ${($_ = isset($this->services['service_locator.a3kzq15']) ? $this->services['service_locator.a3kzq15'] : $this->load('getServiceLocator_A3kzq15Service.php')) && false ?: '_'};
}]));
